// ===== Mock Data for FoodSaver =====

export const mockUsers = {
  customer: {
    id: 'usr_001',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    phone: '+62 812 3456 7890',
    role: 'customer',
    avatar: null,
    created_at: '2024-01-15T08:00:00Z',
  },
  merchant: {
    id: 'usr_002',
    name: 'Budi Santoso',
    email: 'budi@greenplate.id',
    phone: '+62 813 9876 5432',
    role: 'merchant',
    avatar: null,
    merchant: {
      id: 'mrc_001',
      business_name: 'Green Plate Bistro',
      address: 'Jl. Sudirman No. 45',
      city: 'Jakarta',
      category: 'restaurant',
      logo: null,
      is_verified: true,
      rating: 4.8,
      total_reviews: 124,
      operating_hours: '08:00 - 22:00',
      description: 'Farm-to-table restaurant specializing in sustainable cuisine',
    },
    created_at: '2024-01-10T08:00:00Z',
  },
  admin: {
    id: 'usr_003',
    name: 'Admin FoodSaver',
    email: 'admin@foodsaver.id',
    phone: '+62 811 1111 1111',
    role: 'admin',
    avatar: null,
    created_at: '2024-01-01T08:00:00Z',
  },
};

export const mockMerchants = [
  {
    id: 'mrc_001',
    business_name: 'Green Plate Bistro',
    owner_name: 'Budi Santoso',
    email: 'budi@greenplate.id',
    address: 'Jl. Sudirman No. 45',
    city: 'Jakarta',
    category: 'restaurant',
    is_verified: true,
    status: 'active',
    rating: 4.8,
    total_reviews: 124,
    total_products: 12,
    total_orders: 389,
    revenue: 15600000,
    joined_at: '2024-01-10',
  },
  {
    id: 'mrc_002',
    business_name: 'Sunrise Bakery',
    owner_name: 'Ani Wijaya',
    email: 'ani@sunrisebakery.id',
    address: 'Jl. Gatot Subroto No. 12',
    city: 'Jakarta',
    category: 'bakery',
    is_verified: true,
    status: 'active',
    rating: 4.6,
    total_reviews: 89,
    total_products: 8,
    total_orders: 256,
    revenue: 8900000,
    joined_at: '2024-02-05',
  },
  {
    id: 'mrc_003',
    business_name: 'Fresh Market Hub',
    owner_name: 'Dewi Lestari',
    email: 'dewi@freshmarket.id',
    address: 'Jl. Thamrin No. 78',
    city: 'Bandung',
    category: 'grocery',
    is_verified: true,
    status: 'active',
    rating: 4.5,
    total_reviews: 67,
    total_products: 15,
    total_orders: 198,
    revenue: 12300000,
    joined_at: '2024-02-20',
  },
  {
    id: 'mrc_004',
    business_name: 'Sushi Corner',
    owner_name: 'Tanaka Hiroshi',
    email: 'tanaka@sushicorner.id',
    address: 'Jl. Asia Afrika No. 33',
    city: 'Jakarta',
    category: 'restaurant',
    is_verified: false,
    status: 'pending',
    rating: 0,
    total_reviews: 0,
    total_products: 0,
    total_orders: 0,
    revenue: 0,
    joined_at: '2024-06-01',
  },
  {
    id: 'mrc_005',
    business_name: 'Nasi Padang Minang',
    owner_name: 'Rahman Fauzi',
    email: 'rahman@nasiminang.id',
    address: 'Jl. Merdeka No. 10',
    city: 'Surabaya',
    category: 'restaurant',
    is_verified: false,
    status: 'pending',
    rating: 0,
    total_reviews: 0,
    total_products: 0,
    total_orders: 0,
    revenue: 0,
    joined_at: '2024-06-02',
  },
  {
    id: 'mrc_006',
    business_name: 'Kebun Sayur Organik',
    owner_name: 'Lia Putri',
    email: 'lia@kebunsayur.id',
    address: 'Jl. Raya Bogor No. 55',
    city: 'Bogor',
    category: 'grocery',
    is_verified: true,
    status: 'active',
    rating: 4.9,
    total_reviews: 203,
    total_products: 20,
    total_orders: 512,
    revenue: 23400000,
    joined_at: '2024-01-05',
  },
];

export const mockProducts = [
  {
    id: 'prd_001',
    name: 'Surprise Bakery Bag',
    description: 'A delightful assortment of freshly baked pastries, bread, and croissants from today\'s selection. Perfect for breakfast or afternoon tea.',
    merchant_id: 'mrc_002',
    merchant_name: 'Sunrise Bakery',
    merchant_rating: 4.6,
    category: 'bakery',
    original_price: 85000,
    discounted_price: 35000,
    discount_percentage: 59,
    stock: 5,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
    pickup_start: '17:00',
    pickup_end: '19:00',
    pickup_date: 'Today',
    is_active: true,
    created_at: '2024-06-01',
  },
  {
    id: 'prd_002',
    name: 'Nasi Box Special',
    description: 'Complete Indonesian lunch box with rice, rendang, vegetables, sambal, and kerupuk. Generous portions from our daily menu.',
    merchant_id: 'mrc_001',
    merchant_name: 'Green Plate Bistro',
    merchant_rating: 4.8,
    category: 'restaurant',
    original_price: 55000,
    discounted_price: 25000,
    discount_percentage: 55,
    stock: 8,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop',
    pickup_start: '14:00',
    pickup_end: '16:00',
    pickup_date: 'Today',
    is_active: true,
    created_at: '2024-06-01',
  },
  {
    id: 'prd_003',
    name: 'Fresh Veggie Box',
    description: 'Organic seasonal vegetables including kangkung, bayam, tomat, bawang, and cabai. Perfect for home cooking.',
    merchant_id: 'mrc_003',
    merchant_name: 'Fresh Market Hub',
    merchant_rating: 4.5,
    category: 'grocery',
    original_price: 75000,
    discounted_price: 30000,
    discount_percentage: 60,
    stock: 3,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop',
    pickup_start: '16:00',
    pickup_end: '18:00',
    pickup_date: 'Today',
    is_active: true,
    created_at: '2024-06-01',
  },
  {
    id: 'prd_004',
    name: 'Pastry Delight Pack',
    description: 'Mix of Danish pastries, muffins, and cinnamon rolls. All baked fresh this morning.',
    merchant_id: 'mrc_002',
    merchant_name: 'Sunrise Bakery',
    merchant_rating: 4.6,
    category: 'bakery',
    original_price: 120000,
    discounted_price: 45000,
    discount_percentage: 63,
    stock: 4,
    image: 'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?w=400&h=300&fit=crop',
    pickup_start: '18:00',
    pickup_end: '20:00',
    pickup_date: 'Today',
    is_active: true,
    created_at: '2024-06-01',
  },
  {
    id: 'prd_005',
    name: 'Sate Ayam Bundle',
    description: '20 sticks of chicken satay with peanut sauce and lontong. Great for family dinner.',
    merchant_id: 'mrc_001',
    merchant_name: 'Green Plate Bistro',
    merchant_rating: 4.8,
    category: 'restaurant',
    original_price: 80000,
    discounted_price: 35000,
    discount_percentage: 56,
    stock: 6,
    image: 'https://images.unsplash.com/photo-1529563021893-cc83c992d75d?w=400&h=300&fit=crop',
    pickup_start: '17:00',
    pickup_end: '19:30',
    pickup_date: 'Today',
    is_active: true,
    created_at: '2024-06-01',
  },
  {
    id: 'prd_006',
    name: 'Fruit Rescue Box',
    description: 'Assorted tropical fruits: mangoes, papayas, bananas, and pineapples. Slightly cosmetically imperfect but delicious!',
    merchant_id: 'mrc_003',
    merchant_name: 'Fresh Market Hub',
    merchant_rating: 4.5,
    category: 'grocery',
    original_price: 65000,
    discounted_price: 25000,
    discount_percentage: 62,
    stock: 7,
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400&h=300&fit=crop',
    pickup_start: '15:00',
    pickup_end: '17:00',
    pickup_date: 'Today',
    is_active: true,
    created_at: '2024-06-01',
  },
  {
    id: 'prd_007',
    name: 'Organic Salad Bowl',
    description: 'Fresh garden salad with organic greens, cherry tomatoes, avocado, and house dressing.',
    merchant_id: 'mrc_006',
    merchant_name: 'Kebun Sayur Organik',
    merchant_rating: 4.9,
    category: 'grocery',
    original_price: 45000,
    discounted_price: 20000,
    discount_percentage: 56,
    stock: 10,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    pickup_start: '11:00',
    pickup_end: '14:00',
    pickup_date: 'Today',
    is_active: true,
    created_at: '2024-06-01',
  },
  {
    id: 'prd_008',
    name: 'Artisan Bread Basket',
    description: 'Sourdough, whole wheat, and rye bread. Baked with traditional methods using natural fermentation.',
    merchant_id: 'mrc_002',
    merchant_name: 'Sunrise Bakery',
    merchant_rating: 4.6,
    category: 'bakery',
    original_price: 95000,
    discounted_price: 40000,
    discount_percentage: 58,
    stock: 3,
    image: 'https://images.unsplash.com/photo-1549931319-a545753467c8?w=400&h=300&fit=crop',
    pickup_start: '16:00',
    pickup_end: '18:30',
    pickup_date: 'Today',
    is_active: true,
    created_at: '2024-06-01',
  },
];

export const mockOrders = [
  {
    id: 'ord_001',
    order_number: 'FS-20240601-001',
    customer_id: 'usr_001',
    customer_name: 'Sarah Chen',
    product_id: 'prd_001',
    product_name: 'Surprise Bakery Bag',
    merchant_id: 'mrc_002',
    merchant_name: 'Sunrise Bakery',
    quantity: 1,
    original_price: 85000,
    total_price: 35000,
    savings: 50000,
    status: 'picked_up',
    pickup_code: 'FSV-A1B2C3',
    pickup_time: '17:00 - 19:00',
    payment_status: 'paid',
    payment_method: 'gopay',
    created_at: '2024-06-01T10:30:00Z',
    picked_up_at: '2024-06-01T17:45:00Z',
  },
  {
    id: 'ord_002',
    order_number: 'FS-20240602-002',
    customer_id: 'usr_001',
    customer_name: 'Sarah Chen',
    product_id: 'prd_002',
    product_name: 'Nasi Box Special',
    merchant_id: 'mrc_001',
    merchant_name: 'Green Plate Bistro',
    quantity: 2,
    original_price: 110000,
    total_price: 50000,
    savings: 60000,
    status: 'confirmed',
    pickup_code: 'FSV-D4E5F6',
    pickup_time: '14:00 - 16:00',
    payment_status: 'paid',
    payment_method: 'ovo',
    created_at: '2024-06-02T09:15:00Z',
    picked_up_at: null,
  },
  {
    id: 'ord_003',
    order_number: 'FS-20240603-003',
    customer_id: 'usr_001',
    customer_name: 'Sarah Chen',
    product_id: 'prd_003',
    product_name: 'Fresh Veggie Box',
    merchant_id: 'mrc_003',
    merchant_name: 'Fresh Market Hub',
    quantity: 1,
    original_price: 75000,
    total_price: 30000,
    savings: 45000,
    status: 'pending',
    pickup_code: 'FSV-G7H8I9',
    pickup_time: '16:00 - 18:00',
    payment_status: 'pending',
    payment_method: null,
    created_at: '2024-06-03T14:20:00Z',
    picked_up_at: null,
  },
  {
    id: 'ord_004',
    order_number: 'FS-20240603-004',
    customer_id: 'usr_001',
    customer_name: 'Sarah Chen',
    product_id: 'prd_005',
    product_name: 'Sate Ayam Bundle',
    merchant_id: 'mrc_001',
    merchant_name: 'Green Plate Bistro',
    quantity: 1,
    original_price: 80000,
    total_price: 35000,
    savings: 45000,
    status: 'cancelled',
    pickup_code: 'FSV-J0K1L2',
    pickup_time: '17:00 - 19:30',
    payment_status: 'refunded',
    payment_method: 'dana',
    created_at: '2024-06-03T08:00:00Z',
    picked_up_at: null,
  },
  {
    id: 'ord_005',
    order_number: 'FS-20240604-005',
    customer_id: 'usr_001',
    customer_name: 'Sarah Chen',
    product_id: 'prd_007',
    product_name: 'Organic Salad Bowl',
    merchant_id: 'mrc_006',
    merchant_name: 'Kebun Sayur Organik',
    quantity: 1,
    original_price: 45000,
    total_price: 20000,
    savings: 25000,
    status: 'confirmed',
    pickup_code: 'FSV-M3N4O5',
    pickup_time: '11:00 - 14:00',
    payment_status: 'paid',
    payment_method: 'gopay',
    created_at: '2024-06-04T07:30:00Z',
    picked_up_at: null,
  },
];

export const mockMerchantOrders = [
  {
    id: 'ord_101',
    order_number: 'FS-20240604-101',
    customer_name: 'Lisa Permata',
    product_name: 'Nasi Box Special',
    quantity: 2,
    total_price: 50000,
    status: 'pending',
    pickup_code: 'FSV-X1Y2Z3',
    pickup_time: '14:00 - 16:00',
    payment_status: 'paid',
    created_at: '2024-06-04T09:00:00Z',
  },
  {
    id: 'ord_102',
    order_number: 'FS-20240604-102',
    customer_name: 'Ahmad Ridwan',
    product_name: 'Sate Ayam Bundle',
    quantity: 1,
    total_price: 35000,
    status: 'confirmed',
    pickup_code: 'FSV-A9B8C7',
    pickup_time: '17:00 - 19:30',
    payment_status: 'paid',
    created_at: '2024-06-04T10:30:00Z',
  },
  {
    id: 'ord_103',
    order_number: 'FS-20240604-103',
    customer_name: 'Rina Susanti',
    product_name: 'Nasi Box Special',
    quantity: 3,
    total_price: 75000,
    status: 'picked_up',
    pickup_code: 'FSV-D6E5F4',
    pickup_time: '14:00 - 16:00',
    payment_status: 'paid',
    created_at: '2024-06-04T08:15:00Z',
    picked_up_at: '2024-06-04T14:30:00Z',
  },
  {
    id: 'ord_104',
    order_number: 'FS-20240603-104',
    customer_name: 'Joko Widodo',
    product_name: 'Sate Ayam Bundle',
    quantity: 2,
    total_price: 70000,
    status: 'cancelled',
    pickup_code: 'FSV-G3H2I1',
    pickup_time: '17:00 - 19:30',
    payment_status: 'refunded',
    created_at: '2024-06-03T16:00:00Z',
  },
];

export const mockImpact = {
  customer: {
    food_saved_kg: 12.5,
    co2_prevented_kg: 31.2,
    money_saved: 225000,
    total_bags: 8,
    trees_equivalent: 1.4,
    meals_rescued: 15,
    water_saved_liters: 4500,
  },
  platform: {
    food_saved_kg: 15230,
    co2_prevented_kg: 38075,
    money_saved: 456900000,
    total_bags: 12450,
    total_users: 8542,
    total_merchants: 234,
    meals_rescued: 28400,
    trees_equivalent: 1720,
    water_saved_liters: 5472000,
  },
};

export const mockComplaints = [
  {
    id: 'cmp_001',
    order_id: 'ord_001',
    customer_name: 'Sarah Chen',
    merchant_name: 'Sunrise Bakery',
    subject: 'Missing items in bag',
    description: 'The bag was supposed to contain 3 croissants but only had 2.',
    status: 'open',
    priority: 'medium',
    created_at: '2024-06-01T20:00:00Z',
    resolution: null,
  },
  {
    id: 'cmp_002',
    order_id: 'ord_002',
    customer_name: 'Ahmad Ridwan',
    merchant_name: 'Green Plate Bistro',
    subject: 'Food quality issue',
    description: 'The rice was cold and the rendang tasted stale.',
    status: 'in_progress',
    priority: 'high',
    assigned_to: 'Admin FoodSaver',
    created_at: '2024-06-02T18:30:00Z',
    resolution: null,
  },
  {
    id: 'cmp_003',
    order_id: 'ord_003',
    customer_name: 'Lisa Permata',
    merchant_name: 'Fresh Market Hub',
    subject: 'Late pickup window',
    description: 'Store was closed when I arrived during the pickup window.',
    status: 'resolved',
    priority: 'high',
    assigned_to: 'Admin FoodSaver',
    created_at: '2024-05-28T19:00:00Z',
    resolution: 'Full refund issued. Merchant warned about pickup window compliance.',
    resolved_at: '2024-05-29T10:00:00Z',
  },
  {
    id: 'cmp_004',
    order_id: 'ord_004',
    customer_name: 'Dewi Susanti',
    merchant_name: 'Sunrise Bakery',
    subject: 'Wrong order received',
    description: 'I ordered Artisan Bread Basket but received regular bread.',
    status: 'open',
    priority: 'low',
    created_at: '2024-06-03T21:00:00Z',
    resolution: null,
  },
];

export const mockPendingVerifications = [
  {
    id: 'ver_001',
    merchant_id: 'mrc_004',
    business_name: 'Sushi Corner',
    owner_name: 'Tanaka Hiroshi',
    email: 'tanaka@sushicorner.id',
    category: 'restaurant',
    city: 'Jakarta',
    address: 'Jl. Asia Afrika No. 33',
    documents: ['Business License', 'Food Safety Certificate', 'ID Card'],
    submitted_at: '2024-06-01T10:00:00Z',
    status: 'pending',
  },
  {
    id: 'ver_002',
    merchant_id: 'mrc_005',
    business_name: 'Nasi Padang Minang',
    owner_name: 'Rahman Fauzi',
    email: 'rahman@nasiminang.id',
    category: 'restaurant',
    city: 'Surabaya',
    address: 'Jl. Merdeka No. 10',
    documents: ['Business License', 'ID Card'],
    submitted_at: '2024-06-02T14:00:00Z',
    status: 'pending',
  },
];

export const mockAdminStats = {
  total_users: 8542,
  total_merchants: 234,
  active_merchants: 198,
  total_orders: 45230,
  total_revenue: 1567800000,
  pending_verifications: 2,
  open_complaints: 3,
  monthly_growth_users: 12.5,
  monthly_growth_orders: 18.3,
  monthly_growth_revenue: 15.7,
};

export const mockWeeklyRevenue = {
  labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  data: [1200000, 1450000, 980000, 1680000, 2100000, 2450000, 1890000],
};

export const mockMonthlyTrend = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  orders: [3200, 4100, 5400, 6200, 7800, 8900],
  revenue: [98000000, 125000000, 165000000, 189000000, 234000000, 267000000],
};

export const mockMerchantDistribution = {
  labels: ['Restaurant', 'Bakery', 'Grocery', 'Cafe', 'Other'],
  data: [89, 52, 45, 32, 16],
};

export const mockTopMerchants = [
  { name: 'Kebun Sayur Organik', orders: 512, revenue: 23400000, rating: 4.9 },
  { name: 'Green Plate Bistro', orders: 389, revenue: 15600000, rating: 4.8 },
  { name: 'Sunrise Bakery', orders: 256, revenue: 8900000, rating: 4.6 },
  { name: 'Fresh Market Hub', orders: 198, revenue: 12300000, rating: 4.5 },
  { name: 'Kopi Nusantara', orders: 167, revenue: 6700000, rating: 4.4 },
];

export const mockTestimonials = [
  {
    id: 1,
    name: 'Rina Wijaya',
    role: 'Customer',
    avatar: '👩',
    text: 'FoodSaver has completely changed how I think about food waste. I get amazing meals at half the price while helping the environment!',
    rating: 5,
  },
  {
    id: 2,
    name: 'Chef Marco',
    role: 'Restaurant Owner',
    avatar: '👨‍🍳',
    text: 'We used to throw away so much food at the end of the day. Now we sell it through FoodSaver and it\'s a win-win for everyone.',
    rating: 5,
  },
  {
    id: 3,
    name: 'Dian Pratama',
    role: 'Customer',
    avatar: '👨',
    text: 'The surprise bags are the best! It\'s like a culinary adventure every time. Plus, I\'m saving money and the planet.',
    rating: 5,
  },
];

export const productCategories = [
  { value: 'all', label: 'All Categories' },
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'bakery', label: 'Bakery' },
  { value: 'grocery', label: 'Grocery' },
  { value: 'cafe', label: 'Cafe' },
  { value: 'other', label: 'Other' },
];

export const orderStatuses = [
  { value: 'all', label: 'All Status' },
  { value: 'pending', label: 'Pending' },
  { value: 'confirmed', label: 'Confirmed' },
  { value: 'picked_up', label: 'Picked Up' },
  { value: 'cancelled', label: 'Cancelled' },
];

export const formatCurrency = (amount) => {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

export const formatDate = (dateString) => {
  return new Date(dateString).toLocaleDateString('id-ID', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
};

export const formatDateTime = (dateString) => {
  return new Date(dateString).toLocaleDateString('id-ID', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
};

export const getStatusColor = (status) => {
  const colors = {
    pending: 'warning',
    confirmed: 'info',
    picked_up: 'success',
    completed: 'success',
    cancelled: 'error',
    active: 'success',
    inactive: 'neutral',
    open: 'error',
    in_progress: 'warning',
    resolved: 'success',
  };
  return colors[status] || 'neutral';
};

export const getStatusLabel = (status) => {
  const labels = {
    pending: 'Pending',
    confirmed: 'Confirmed',
    picked_up: 'Picked Up',
    completed: 'Completed',
    cancelled: 'Cancelled',
    active: 'Active',
    inactive: 'Inactive',
    open: 'Open',
    in_progress: 'In Progress',
    resolved: 'Resolved',
  };
  return labels[status] || status;
};
